### ISSUE TITLE
R functions in parallel

### ISSUE THREAD

**Issue by jsta** [wrathematics/RparallelGuide#1]
Maybe it is my beginner status here, but I was confused when you spent a great deal of time showing Rcpp functions run in parallel and then you say this:

"you can't call R functions in parallel. Well I mean, you can, but you shouldn't. So if you're using Rcpp, you need to be careful about calling other "Rcpp functions" (which are really R functions in disguise)."

To me you are saying, don't run Rcpp in parallel but I don't think that is what you mean.

**Comment by wrathematics** [comment]
In my defense, it was not written sober; I'm surprised any of it is coherent.

What I mean is you can't call an Rcpp function in parallel.  Within a function, you can parallelize your `for` loops, but those `for` loops should not themselves call Rcpp functions.  Really you shouldn't call other C-level R functions, and Rcpp functions are just examples of this.  So it's not a defect of Rcpp as much as the R memory allocator.

I'll probably revise the text to be more clear at some point.

**Comment by wrathematics** [comment]
This should hopefully be clarified in the latest version of the document.

Thanks for bringing this to my attention; if you still find the section (now 5.1) unclear, please let me know.
