### ISSUE TITLE
TBB misleading

### ISSUE THREAD

**Issue by dselivanov** [wrathematics/RparallelGuide#3]
Article is quite helpful, but it contains misleading facts.

> There's also Intel Thread Building Blocks (TBB). TBB has some really cool ideas in it, but it's not portable (Intel only), and frankly by my assessment, it's pretty dead. I don't work for Intel, or have any special insight into how they do things, but I'm 99% sure they're just giving up on TBB in favor of OpenMP, which is a real and proper standard (supported deeply by Intel, no less). The various parallel Rcpp efforts, like RcppParallel seem to be heading towards utilizing TBB (because they all use Macs, and Clang only recently got its act together on OpenMP). JJ's a super duper smart guy, but I really think he's betting on the wrong horse here.
1. TBB is not dead, as you can from their release history.
2. TBB **is portable**. And in fact more portable then OpenMP, because it is not language extension, but _library_. You can easily use tbb on any x86/x64 platforms and even on ARM. Just google a little bit.
3. As I understand, RcppParallel is built on top of TBB for the following reasons:
   1. Cross platform - works even on windows.
   2. It is much more natural to use it **C++**, not C.
4. You can easily install `clang-omp` or modern `gcc` on OS X, so this is not an issue at all.

**Comment by wrathematics** [comment]
Thanks for the report, but I flatly disagree with some of your characterizations.
1. Perhaps calling it dead is unfair or unjustified.  My comment was based on personal interactions with people at or close to Intel, and it's entirely possible I misunderstood what I was being told.  I'm happy to cede this point, as I actually think TBB has a lot of great ideas in it.
2. TBB is not completely processor independent, period.  And I think by any reasonable definition, it is _less portable_ than OpenMP.  OpenMP is a language extension implemented as a library, and is accessible to users across different hardware, operating systems (yes, even Windows), and programming languages, namely C, C++, and Fortran.

3-4. I don't claim to speak for JJ or RStudio.  But when they started writing RcppParallel well over a year ago, there was no such thing as a functioning OpenMP available to clang.

**Comment by dselivanov** [comment]
Interesting, will try check whether RTools suppot openmp on windows.
But from my experience it is much more simple to develop portable cross-platform package with TBB + RcppParallel than OpenMP. 
But of course it is more simple to write single `#pragma` directive to parallelise `for` loop, then write `parallelFor` or `parallelReduce` functor.
I think it worth to add  `RcppParallel` to article as good alternative to `OpenMP`.
Feel free to close this issue.

**Comment by dselivanov** [comment]
After I got more practice in more projects, I'm going to agree with you - in most cases openmp is sufficient. Tbb provides more data structures and allow to elegantly solve some problems, but in more than 90% cases openmp is much more simpler to use.
